### ISSUE TITLE
Feature - Hide chat bot messages in on-screen chat

### ISSUE THREAD

**Issue by deathpax** [MichaelJolley/io#126]
To prevent clutter, perhaps hide messages from the chat bot in the on-screen chat window.

**Comment by MichaelJolley** [comment]
Done deal. Got it pushed tonight.  Thanks for the idea @deathpax!

![bitmoji](https://render.bitstrips.com/v2/cpanel/b2adcf31-8a3d-457b-8b87-9ac5aad8d214-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)
