### ISSUE TITLE
Add a !awesome-whodis command

### ISSUE THREAD

**Issue by cmjchrisjones** [MichaelJolley/io#138]
A quick command to link of to a clip explaining what the project is for

**Comment by cmjchrisjones** [comment]
Did you manage to do a video clip for this? If so I can quickly put a PR in for this ;)

**Comment by MichaelJolley** [comment]
@cmjchrisjones theres a clip for this now.  I’m not in a place where I can look for it but it’s fairly recent.

**Comment by cmjchrisjones** [comment]
That is going to be my next PR - should be incoming fairly shortly :)

**Comment by cmjchrisjones** [comment]
Closing this issue as its now been merged
