### ISSUE TITLE
Need to specify a user throttle for A/V commands 

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/io#23]

**Comment by CodemanCodes** [comment]
I've started work on this and wanted to run a few things by you.

The way I've done this is by adding the throttle to the env file. Then in the twitch chat class when a av command is handled, set a last-run variable.  Before handling the av command I check if the limit has passed. I'm also checking if the user is the broadcaster or a mod, if so, allow the command regardless of the throttle setting.

Is there a different way you would want that handled?

**Comment by MichaelJolley** [comment]
I think that sounds good.  Once we start storing more in a database with an "admin" site we'll probably want to move it there, but that's a great start!

**Comment by MichaelJolley** [comment]
Rather than throttling all sound by x timeframe, throttle per user sounds by x timeframe.

**Comment by MichaelJolley** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/b2adcf31-8a3d-457b-8b87-9ac5aad8d214-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)
