### ISSUE TITLE
Inaccurate response to wrong theme command

### ISSUE THREAD

**Issue by parithon** [MichaelJolley/io#30]
The current response reads: "**%username%, 1 is not a valid theme name or isn't installed. You can use !theme to get a list of available themes.**"

I believe we changed the command to get the list of themes to: **!theme list**.

**Comment by MichaelJolley** [comment]
Thank you for your input.  But for the first time in history, @parithon is incorrect.

![bitmoji](https://render.bitstrips.com/v2/cpanel/19bb15ab-b2f4-4ea8-8360-52110d6a18b9-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)

`!theme` is the command that whispers the list of themes.  `!theme list` has been deprecated.  Please update your nuget packages yo.

**Comment by parithon** [comment]
Not only that, I put the non-bug on the wrong repo... note to self, more sleep needed. LUL
