### ISSUE TITLE
Auto shoutout

### ISSUE THREAD

**Issue by copperbeardy** [MichaelJolley/io#41]
Implement  auto shout of when other live coders enter chat

**Comment by MichaelJolley** [comment]
@all-contributors please add @copperbeardy for ideas

**Comment by MichaelJolley** [comment]
I like this idea a lot.  Maybe you (@copperbeardy) and others can help work through what we'd need. On first blush I'd say we need:

- [ ] Ability to identify who the team members are
- [ ] Store team members in db
- [x] Write message to chat welcoming team member

**Comment by parithon** [comment]
It may prove difficult to satisfy bullet point one as the helix API does not implement any way to get this information. Kraken does (https://api.twitch.tv/api/teams/[team]) but it is deprecated and nobody knows when it will eventually stop working.

![bitmoji](https://render.bitstrips.com/v2/cpanel/0387b63d-2dff-48ad-ba43-2bba55c8155e-b427cfda-a7f5-497f-a483-1061dc3d44a5-v1.png?transparent=1&palette=1&width=246)
