### ISSUE TITLE
!embed command (maybe?)

### ISSUE THREAD

**Issue by Flyken271** [MichaelJolley/io#42]
Just an idea I had, but maybe add a command for an embed, by embed I mean a little "material design" box that pops up maybe next to chat for a second or two, where people can post a little embed with a sound attached, for example:

!embed FlykensEmbed: "Hello all :D" !jeopardy;

arg layout: !embed Title:[string]: Description[string] SoundFX[command, optional]

**Comment by MichaelJolley** [comment]
Design from @Flyken271:

![image](https://user-images.githubusercontent.com/1228996/61332266-7560af80-a7e9-11e9-80b3-b0359d7d2466.png)

**Comment by MichaelJolley** [comment]
@all-contributors please add @Flyken271 for ideas

**Comment by MichaelJolley** [comment]
I'm going to close this one for now but thank you for the idea!

I think you can use !{sfx} text here to do something similar to playing audio with a message.  I don't know that I want even more flying out to cover the screen.

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)
