### ISSUE TITLE
Handle items with no items (EG Raid)

### ISSUE THREAD

**Issue by cmjchrisjones** [MichaelJolley/io#49]
I've just been looking at Sunday's show notes and noticed that because there was no raid, it displays the header and an empty row, which makes it look a bit weird in my opionion

![image](https://user-images.githubusercontent.com/3969086/61671631-6776c700-ace0-11e9-859d-292f3e62ba07.png)

I guess there are a couple options at first thought which could be used if its decided to fix:

1: Don't add the raid section at all until there has been a raid (EG add the header, draw the table header on the first raid, subsequent raids just add a row to the table)
2: Keep the title there but instead of the table being displayed show *N/A* or *No raids*

Chances are this might also happen for cheers and maybe some other sections...

**Comment by MichaelJolley** [comment]
Yeah I've been torn on this one.  In the past I've either added an empty row to show an empty table or just removed it.  I'm not sure which would be better.

It's helpful to have an empty table if something went wrong and I have to manually update the table, but that's happening less frequently now that it's working well.

**Comment by MichaelJolley** [comment]
It appears that only the raid section was doing this.  We check for other items before writing them.  Cleaned up, committed & pushed.

![bitmoji](https://render.bitstrips.com/v2/cpanel/b2adcf31-8a3d-457b-8b87-9ac5aad8d214-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)
