### ISSUE TITLE
We should change to using Typescript Project References

### ISSUE THREAD

**Issue by parithon** [MichaelJolley/io#56]
Instead of including multiple source roots within our `tsconfig.json` we should take advantage of the newer [Typescript 3.0 Project References](https://devblogs.microsoft.com/typescript/announcing-typescript-3-0/#project-references).

**Comment by MichaelJolley** [comment]
I like that.  I'm curious how it would work with what we learned tonight on @mtheoryx's stream.

**Comment by parithon** [comment]
I think it would work better because we're not copying files in each of the services. We would build the 'common' files in the lower layer and the *.d.ts files would be used in the subsequent higher layers. Therefore the common files would build once, in the Docker build pipeline, and the dependent services (chat, stream-notes, etc.) will simply look at the reference and utilize the already built files.

**Comment by MichaelJolley** [comment]
I think what's baking my noodle is (take the API service for example) we're copying in the API & Common code in the Dockerfile.  My understanding there is that when we build it only has that code.  So I guess we have a Common image that contains a built common project.  Then use that image as the base for API.  So the built common code is where?  Where it would have been copied in our current Dockerfile?

**Comment by mtheoryx** [comment]
@MichaelJolley You may have already looked into this, but you would want to use a multistage build. Once you build the common ts files, you start with a new node alpine image and within the docker file, you copy from that previous layer only the already built image.

The nice thing is that once you do that for one container, all those common layers will be cached on your machine, ready for all the other containers.

**Comment by MichaelJolley** [comment]
@mtheoryx yes!  I'm actually working on having a "base" image for common code that would be used by other services to build from.  My plan is to have an image to build and then copy the output to a "final" base image with just the output and no source code.  Are we on the same page there?
